spring:
  profiles:
    include: ConfigureSecurity, InjectSeedData, SwaggerEnabled, EnableMessageQueueIntegration
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=elevennyilvantartas
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: .sasasasa.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    labels: test
  data:
    ldap:
      repositories:
        enabled: true
