server:
  port: 8099
  servlet:
    context-path: /
  max-http-header-size: 1024KB

spring:
  profiles:
    active: development
  application:
    name: Eleven-Nyilvantartas
  jmx:
    default-domain: elevennyilvantartas
  liquibase:
    change-log: classpath:/migration/liquibase-changelog.xml
    labels: "!test"
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_prefix: N_
            audit_table_suffix: ""
            revision_field_name: ID_VERZIO
            revision_type_field_name: VERZIO_TIPUS
            revission_on_collection_change: true
            store_data_at_delete: true
    hibernate:
      use-new-id-generator-mappings: false
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
management:
  endpoints:
    web:
      exposure:
        include: info, health
