CREATE TABLE IF NOT EXISTS OPERATOR (
	ID              BIGINT          NOT NULL DEFAULT nextval('seq_operator'),
	VEZETEK_NEV     VARCHAR(50)     NOT NULL,
	KERESZT_NEV     VARCHAR(50)     NOT NULL,
	USERNAME        VARCHAR(50)     NOT NULL,
	PASSWORD        VARCHAR(50)     NOT NULL,
	STATUS          VARCHAR(1)      NOT NULL DEFAULT 'A',
	MODOSITAS       TIMESTAMP (6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	JOGOK_FK        BIGINT          NOT NULL,
	CONSTRAINT PK_OPERATOR PRIMARY KEY (ID),
	CONSTRAINT FK_OPERATOR_JOG FOREIGN KEY (jogok_fk) REFERENCES JOGOK (id)
);

CREATE TABLE IF NOT EXISTS N_OPERATOR (
	ID              BIGINT          NOT NULL,
	ID_VERZIO       BIGINT          NOT NULL,
	VERZIO_TIPUS    SMALLINT,
	VEZETEK_NEV     VARCHAR(50),
	KERESZT_NEV     VARCHAR(50),
	USERNAME        VARCHAR(50),
	PASSWORD        VARCHAR(50),
	STATUS          VARCHAR(1),
	MODOSITAS       TIMESTAMP (6),
    JOGOK_FK        BIGINT,
    CONSTRAINT PK_N_OPERATOR PRIMARY KEY (ID_VERZIO, ID)
);
