CREATE TABLE IF NOT EXISTS JOG (
	ID              BIGINT          NOT NULL DEFAULT nextval('seq_jog'),
	CODE            VARCHAR(50)     NOT NULL,
	MEGNEVEZES      VARCHAR(50)     NOT NULL,
	STATUS          VARCHAR(1)      NOT NULL DEFAULT 'A',
	MODOSITAS       TIMESTAMP (6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	CONSTRAINT PK_JOG PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS N_JOG (
	ID              BIGINT          NOT NULL,
	ID_VERZIO       BIGINT          NOT NULL,
	VERZIO_TIPUS    SMALLINT,
	CODE            VARCHAR(50),
	MEGNEVEZES      VARCHAR(50),
	STATUS          VARCHAR(1),
	MODOSITAS       TIMESTAMP (6),
	CONSTRAINT PK_N_JOG PRIMARY KEY (ID_VERZIO, ID)
);
